---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: epopeyaos
# description will be included in the image's metadata
description: EpopeyaOS - This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: akmods
    base: main
    nvidia-driver: nvidia-open
    install: []

  - type: dnf
    install:
      packages:
        - wine
        - wine-mono
        - steam-devices

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.gnome.Loupe
          - com.valvesoftware.Steam
          - com.discordapp.Discord
          - com.spotify.Client
          - org.vinegarhq.Sober
          - org.prismlauncher.PrismLauncher
          - net.lutris.Lutris
          - io.podman_desktop.PodmanDesktop
          - com.jetbrains.IntelliJ-IDEA-Community
          - com.jetbrains.CLion
          - com.jetbrains.WebStorm
          - com.jetbrains.DataGrip
      - scope: user # Also add Flathub user repo, but no user packages
  
  - type: script
    snippets:
      - |
        echo "Añadiendo repositorio de Microsoft VSCode..."
        rpm --import https://packages.microsoft.com/keys/microsoft.asc
        cat <<EOF > /etc/yum.repos.d/vscode.repo
        [code]
        name=Visual Studio Code
        baseurl=https://packages.microsoft.com/yumrepos/vscode
        enabled=1
        gpgcheck=1
        gpgkey=https://packages.microsoft.com/keys/microsoft.asc
        EOF
        echo "Instalando VSCode..."
        dnf install -y code

  - type: gnome-extensions
    install:
      - 307 # Dash to Dock
      - 1460 # Vitals
      - 2087 # Desktop Icons NG (DING)
      - 7065 # Tiling Shell
      - 1262 # Bing Wallpaper 

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
